// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase: ReturnType<typeof createClient<Database>>;

// Only initialize if both URL and key are present
if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
} else {
  // Create a stub client that won't be used - prevents errors
  supabase = createClient<Database>("https://stub.supabase.co", "stub-key", {
    auth: {
      storage: localStorage,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

export { supabase };
